apiVersion: v1
kind: Service
metadata:
  name: sys-info-nodeport
  labels:
    app: sys-info
spec:
  type: NodePort
  selector:
    app: sys-info
  ports:
    - protocol: TCP
      port: 80        # ClusterIP port
      targetPort: 5000
      nodePort: 30080 # Node port (must be in the 30000-32767 range)
