apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard # Use your cluster's default SC name
  resources:
    requests:
      storage: 200Mi