apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels:
    app: busybox-pod
    environment: dev
spec:
  containers:
    - name: busybox-container
      image: busybox:latest
      command: ["sh", "-c", "echo Hello from BusyBox && sleep 3600"]
