apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: app-container
    image: alpine
    command: ["sh", "-c", "ls /etc/db-credentials && sleep 3600"]
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: DB_USER
    volumeMounts:
    - name: secret-vol
      mountPath: /etc/db-credentials
      readOnly: true
  volumes:
  - name: secret-vol
    secret:
      secretName: db-credentials