apiVersion: apps/v1
kind: Deployment
metadata:
  name: sys-info-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sys-info
  template:
    metadata:
      labels:
        app: sys-info
    spec:
      containers:
      - name: sys-info-container
        image: sachinthokal/flask-sys-info-app:v1.0.1
        ports:
        - containerPort: 5000
